In [2]:
import numpy as np

In [10]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [12]:
arr[8]

8

In [14]:
arr[1:5]

array([1, 2, 3, 4])

In [16]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [18]:
arr[:5]

array([0, 1, 2, 3, 4])

In [20]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
# broadcastin re-assingment

In [24]:
arr[0:5] = 100 # not possible with normal array

In [26]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
# Broadcasting affects the orignal array
arr = np.arange(0,11)

In [30]:
slice_of_arr = arr[0:5]

In [32]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
slice_of_arr[:] = 99

In [38]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [41]:
arr # above slicing affected the orginial array because it points to the array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [52]:
# Do it in a way that it doesn't affects the orginial array
arr = np.arange(1,11)
arr_copy = arr.copy()

In [53]:
slice_of_arr = arr_copy[0:5]

In [54]:
slice_of_arr[:] = 99

In [55]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [58]:
arr # not affected the original array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d.shape

(3, 3)

In [69]:
arr_2d[0,2] # 0 row's 2nd index element

15

In [72]:
arr_2d[:2,1:] # from row intial : to 2nd row k 1st to last index elements

array([[10, 15],
       [25, 30]])

In [74]:
arr = np.array

In [75]:
arr = np.arange(1,11)

In [77]:
arr > 4 # return true value where value is greateer than 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
bool_arr = arr > 4 # creating a boolean array of it

In [82]:
arr[bool_arr] # returing value of array where bool_arr is true

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4] # same as above