In [1]:
# NumPy Arrays

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3,4]

In [5]:
type(mylist)

list

In [11]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] #Two dimensional array

In [15]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:

type(np.array(my_matrix))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
 np.arange(0,10) # Same as python range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,100,10) # With step size

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.zeros(5) # creating array of 5 elements all zeros

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,5)) # 3 rows and 5 coloumns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(4) # returns array with 4 elements all ones

array([1., 1., 1., 1.])

In [32]:
np.ones((4,4)) # returns 2d array of 4x4 all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.linspace(0,5,21) # creates an array including equally spaced 21 digits between 0 to 5(including) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [38]:
len(np.linspace(0,5,21))

21

In [ ]:
np.eye(5) # creates an identity 5x5 matrix

In [40]:
# creating random datas

In [41]:
np.random.rand(2) # np included library -> random(through random number) -> specifies random number will lie between 0 and 1(exculsive) # input value will return 2 numbers inside the array

array([0.06617638, 0.60680903])

In [43]:
np.random.rand(5,2) # retrun array of 5x2 with all number between 0 and 1(exculsive)

array([[0.26977716, 0.47628203],
       [0.49917692, 0.24332033],
       [0.9746322 , 0.37942844],
       [0.00366748, 0.13388697],
       [0.38377797, 0.63854287]])

In [45]:
# randn function return of standard distribution -> with 0 mean and 1 as variance
np.random.randn(5)
np.random.randn(5,3)

array([[-0.45055666, -1.08863245, -0.70076396],
       [ 1.10137182,  0.65742263, -0.24523549],
       [-1.10417802, -0.44538183,  2.27238318],
       [ 0.25796087, -1.73518946,  0.08635971],
       [ 1.31387405, -0.94221882, -0.52400074]])

In [49]:
# return random values between (a,b(exclusive),number of values)
np.random.randint(0,101,5)

array([69, 68, 66, 72, 21])

In [52]:
# how to fix the value random output
np.random.seed(432)
np.random.rand(4)

array([0.90366057, 0.89601028, 0.58995011, 0.98727338])

In [56]:
np.random.seed(432)
np.random.rand(4) # same output because these output are associated with seed = 432

array([0.90366057, 0.89601028, 0.58995011, 0.98727338])

In [57]:
## Common attributes in NumPy ##

In [63]:
arr = np.arange(0,125)

In [65]:
arr.reshape(5,5,5) # reshaped the 1D array into 3D array 

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [69]:
ranarr = np.random.randint(1,10,5)
ranarr

array([7, 8, 1, 7, 2])

In [71]:
ranarr.min() # returns minimum element in the array

1

In [73]:
ranarr.max() # returns maximum element in the array

8

In [75]:
ranarr.argmax() # returns index of maximum element in the array

1

In [77]:
ranarr.argmin() # returns index of minimum element in the array

2

In [80]:
arr.shape

(125,)

In [81]:
arr.reshape(5,5,5)

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])